# DQN Config for Agent 1 - Simple Event Mapping

env_id: OpenTheChests-v0
algorithm: DQN

# Model
learning_rate: 0.001

# Training
total_timesteps: 50000
save_path: agent1_patterns_chests_to_reach/approach1_simple_event_mapping/weights/agent1_simple_dqn.zip
log_path: agent1_patterns_chests_to_reach/approach1_simple_event_mapping/logs/dqn/
